GET https://httpbin.org/ip
Accept: application/json

###

POST https://httpbin.org/post
Content-Type: application/json

{
  "ide": "PhpStorm",
  "version": "2019.3",
  "releaseDate": "2019-11-28T09:00"
}
