POST https://httpbin.org/post
Content-Type: application/json

{
  "ide": "PhpStorm",
  "version": 2019.3,
  "build": "EAP #3"
}

###

GET https://jetbrains.com

###

GET https://swapi.co/api/starships/

###

GET 
